version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@db:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=ticket_user
      - SPRING_DATASOURCE_PASSWORD=ticket_password
    depends_on:
      - db

  db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=oracle
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  oracle-data:
